#!/bin/sh

export PATH=$PATH:/usr/bin/wget
arg1=$(echo "Quem ri por último ri melhor." | apertium pt-gl)
if test "$arg1" = "Quen rin por último rin mellor."
then
    echo "Test 1 passed! ..."
else
    echo "$arg1 is not equal Quen rin por último rin mellor!"
    exit 1
fi
