#!/bin/bash
set -e

apt-get -qy update -o Dir::Etc::sourcelist="sources.list.d/apertium-nightly.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
apt-get -qfy install cg3 giella-kal
su - katersat -c '~/workbench/inc/sanity-check.php'

pushd $AUTOPKG_HOME
. speller-funcs.sh
pkg_spellers Kukkuniiaat
popd
